POST {{host}}/ru/prod/tokens/v2/oauth
Accept: application/json
Content-Type: application/json
X-IBM-Client-Id: {{client_id}}
RqUID: {{unique_id}}
Authorization: Bearer {{access_token}}

{
    "rq_uid": "{{unique_id}}",
    "rq_tm": "2021-08-23T17:59:00Z",
    "member_id": "{{member_id}}",
    "id_qr": "{{terminal_id}}",
    "order_number": "1234",
    "order_sum": 100,
    "order_create_date": "2021-08-23T17:59:00Z",
    "currency": "643"
}
